from typing import Protocol


class AndroidDriver(Protocol):
    async def tap_by_text(self, text: str) -> bool: ...
    async def tap_by_resource_id(self, resource_id: str) -> bool: ...
    async def type_text(self, text: str) -> None: ...
    async def send_current_text(self) -> bool: ...
    async def take_screenshot(self) -> str: ...
    async def swipe_up(self) -> None: ...
    async def back(self) -> None: ...
